# Generated by Django 4.1 on 2023-10-25 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="book",
            name="id",
        ),
        migrations.AddField(
            model_name="book",
            name="owned",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="book",
            name="title_author",
            field=models.CharField(
                default="CustomDefaultValue",
                max_length=200,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
