# Generated by Django 4.1 on 2023-10-29 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0004_remove_book_thumbnail"),
    ]

    operations = [
        migrations.RenameField(
            model_name="book",
            old_name="title_author",
            new_name="id",
        ),
    ]
