# Generated by Django 4.1 on 2023-10-29 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0005_rename_title_author_book_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="book",
            name="owned",
        ),
    ]
