# Generated by Django 4.1 on 2023-10-30 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0006_remove_book_owned"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="year",
            field=models.IntegerField(null=True),
        ),
    ]
