# Generated by Django 4.1 on 2023-11-01 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0008_alter_book_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="embedding",
            field=models.BinaryField(null=True),
        ),
    ]
