# Generated by Django 4.1 on 2023-11-28 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0010_remove_book_embedding"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="embedding",
            field=models.BinaryField(null=True),
        ),
    ]
